### ISSUE TITLE
ラベルプリントの文字を見やすく変更お願いします。

### ISSUE THREAD

**Issue by tsubasamatsumoto** [DecodeLLC/seiren-ios#76]
![img_3380](https://cloud.githubusercontent.com/assets/19566850/25364679/ffcaee40-299e-11e7-9010-92b5b6d6d75f.JPG)

左側の文字を見やすくしてほしい

**Comment by alexeypolitov** [comment]
@tsubasamatsumoto 修正しました。アップデートでご確認ください

**Comment by tsubasamatsumoto** [comment]
OKです。QRの大きさはQRに入れ込む情報量に合わせ今後変えていきましょう。
