### ISSUE TITLE
ラベルのQRの大きさを大きくしてください

### ISSUE THREAD

**Issue by tsubasamatsumoto** [DecodeLLC/seiren-ios#83]
お客さんが使う箇所なのでトラブル（シワ、汚れ、かすれ）による読み込不良を予防したいため

**Comment by alexeypolitov** [comment]
<img width="335" alt="screen shot 2017-08-08 at 10 57 53" src="https://user-images.githubusercontent.com/3468058/29053022-74fa0fbc-7c28-11e7-9bad-2cc15b2b5d7c.png">

@tsubasamatsumoto 大きくしました

**Comment by tsubasamatsumoto** [comment]
QRコードが大きくなったことを確認できました。
